In [68]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import neighbors
from sklearn.metrics import accuracy_score
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [70]:
#Q1_coverting to data frame
iris = pd.read_csv("C:/Users/acer/Desktop/HW2_9823033/Iris.csv")
#print(iris)
titanic=pd.read_csv("C:/Users/acer/Desktop/HW2_9823033/titanic.csv")
print(titanic)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [58]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    150 non-null    int64
 1   Class         150 non-null    int64
 2   Petal length  150 non-null    int64
 3   Sepal length  150 non-null    int64
 4   Sepal width   150 non-null    int64
 5   Petal width   150 non-null    int64
dtypes: int64(6)
memory usage: 7.2 KB

In [59]:
iris.head(10)

   Unnamed: 0  Class  Petal length  Sepal length  Sepal width  Petal width
0           0      1            51            35           14            2
1           1      1            49            30           14            2
2           2      1            47            32           13            2
3           3      1            46            31           15            2
4           4      1            50            36           14            2
5           5      1            54            39           17            4
6           6      1            46            34           14            3
7           7      1            50            34           15            2
8           8      1            44            29           14            2
9           9      1            49            31           15            1

In [60]:
iris.drop("Unnamed: 0",axis=1,inplace=True)
x=iris.drop('Class',axis=1)

In [61]:
x.head(10)

   Petal length  Sepal length  Sepal width  Petal width
0            51            35           14            2
1            49            30           14            2
2            47            32           13            2
3            46            31           15            2
4            50            36           14            2
5            54            39           17            4
6            46            34           14            3
7            50            34           15            2
8            44            29           14            2
9            49            31           15            1

In [62]:
Y=iris['Class']

In [63]:
x_train,x_test,Y_train,Y_test=train_test_split(x,Y,test_size=0.3)
print(x_train.shape,x_test.shape,Y_train.shape,Y_test.shape)

(105, 4) (45, 4) (105,) (45,)

In [64]:
classifier=neighbors.KNeighborsClassifier()

In [65]:
classifier.fit(x_train,Y_train)
pr=classifier.predict(x_test)

In [67]:
acc=accuracy_score(Y_test,pr)
print(acc)

0.9777777777777777

In [76]:
titanic.dropna()
cabins=titanic.loc[:,['Cabin']]
print(cabins)

    Cabin
0     NaN
1     C85
2     NaN
3    C123
4     NaN
..    ...
886   NaN
887   B42
888   NaN
889  C148
890   NaN

[891 rows x 1 columns]

In [77]:
arr_cabin=array(cabins)
print(arr_cabin)

[[nan]
 ['C85']
 [nan]
 ['C123']
 [nan]
 [nan]
 ['E46']
 [nan]
 [nan]
 [nan]
 ['G6']
 ['C103']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['D56']
 [nan]
 ['A6']
 [nan]
 [nan]
 [nan]
 ['C23 C25 C27']
 [nan]
 [nan]
 [nan]
 ['B78']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['D33']
 [nan]
 ['B30']
 ['C52']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B28']
 ['C83']
 [nan]
 [nan]
 [nan]
 ['F33']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['F G73']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C23 C25 C27']
 [nan]
 [nan]
 [nan]
 ['E31']
 [nan]
 [nan]
 [nan]
 ['A5']
 ['D10 D12']
 [nan]
 [nan]
 [nan]
 [nan]
 ['D26']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C110']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B58 B60']
 [nan]
 [nan]
 [nan]
 [nan]
 ['E101']
 ['D26']
 [nan]
 [nan]
 [nan]
 ['F E69']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['D47']
 ['C123']
 [nan]
 ['B86']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['F2']
 [nan]
 [nan]
 ['C2']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['E33']
 [nan]
 [nan]
 [nan]
 ['B19']
 [nan]
 [nan]
 [nan]
 ['A7']
 [nan]
 [nan]
 ['C49']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['F4']
 [nan]
 ['A32']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['F2']
 ['B4']
 ['B80']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['G6']
 [nan]
 [nan]
 [nan]
 ['A31']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['D36']
 [nan]
 [nan]
 ['D15']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C93']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C83']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C78']
 [nan]
 [nan]
 ['D35']
 [nan]
 [nan]
 ['G6']
 ['C87']
 [nan]
 [nan]
 [nan]
 [nan]
 ['B77']
 [nan]
 [nan]
 [nan]
 [nan]
 ['E67']
 ['B94']
 [nan]
 [nan]
 [nan]
 [nan]
 ['C125']
 ['C99']
 [nan]
 [nan]
 [nan]
 ['C118']
 [nan]
 ['D7']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['A19']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B49']
 ['D']
 [nan]
 [nan]
 [nan]
 [nan]
 ['C22 C26']
 ['C106']
 ['B58 B60']
 [nan]
 [nan]
 [nan]
 ['E101']
 [nan]
 ['C22 C26']
 [nan]
 ['C65']
 [nan]
 ['E36']
 ['C54']
 ['B57 B59 B63 B66']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C7']
 ['E34']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C32']
 [nan]
 ['D']
 [nan]
 ['B18']
 [nan]
 ['C124']
 ['C91']
 [nan]
 [nan]
 [nan]
 ['C2']
 ['E40']
 [nan]
 ['T']
 ['F2']
 ['C23 C25 C27']
 [nan]
 [nan]
 [nan]
 ['F33']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C128']
 [nan]
 [nan]
 [nan]
 [nan]
 ['E33']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['D37']
 [nan]
 [nan]
 ['B35']
 ['E50']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C82']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B96 B98']
 [nan]
 [nan]
 ['D36']
 ['G6']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C78']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['E10']
 ['C52']
 [nan]
 [nan]
 [nan]
 ['E44']
 ['B96 B98']
 [nan]
 [nan]
 ['C23 C25 C27']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['A34']
 [nan]
 [nan]
 [nan]
 ['C104']
 [nan]
 [nan]
 ['C111']
 ['C92']
 [nan]
 [nan]
 ['E38']
 ['D21']
 [nan]
 [nan]
 ['E12']
 [nan]
 ['E63']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['D']
 [nan]
 ['A14']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B49']
 [nan]
 ['C93']
 ['B37']
 [nan]
 [nan]
 [nan]
 [nan]
 ['C30']
 [nan]
 [nan]
 [nan]
 ['D20']
 [nan]
 ['C22 C26']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B79']
 ['C65']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['E25']
 [nan]
 [nan]
 ['D46']
 ['F33']
 [nan]
 [nan]
 [nan]
 ['B73']
 [nan]
 [nan]
 ['B18']
 [nan]
 [nan]
 [nan]
 ['C95']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B38']
 [nan]
 [nan]
 ['B39']
 ['B22']
 [nan]
 [nan]
 [nan]
 ['C86']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C70']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['A16']
 [nan]
 ['E67']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C101']
 ['E25']
 [nan]
 [nan]
 [nan]
 [nan]
 ['E44']
 [nan]
 [nan]
 [nan]
 ['C68']
 [nan]
 ['A10']
 [nan]
 ['E68']
 [nan]
 ['B41']
 [nan]
 [nan]
 [nan]
 ['D20']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['A20']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C125']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['F4']
 [nan]
 [nan]
 ['D19']
 [nan]
 [nan]
 [nan]
 ['D50']
 [nan]
 ['D9']
 [nan]
 [nan]
 ['A23']
 [nan]
 ['B50']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B35']
 [nan]
 [nan]
 [nan]
 ['D33']
 [nan]
 ['A26']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['D48']
 [nan]
 [nan]
 ['E58']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C126']
 [nan]
 ['B71']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B51 B53 B55']
 [nan]
 ['D49']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B5']
 ['B20']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C68']
 ['F G63']
 ['C62 C64']
 ['E24']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['E24']
 [nan]
 [nan]
 ['C90']
 ['C124']
 ['C126']
 [nan]
 [nan]
 ['F G73']
 ['C45']
 ['E101']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['E8']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B5']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B101']
 [nan]
 [nan]
 ['D45']
 ['C46']
 ['B57 B59 B63 B66']
 [nan]
 [nan]
 ['B22']
 [nan]
 [nan]
 ['D30']
 [nan]
 [nan]
 ['E121']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B77']
 [nan]
 [nan]
 [nan]
 ['B96 B98']
 [nan]
 ['D11']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['E77']
 [nan]
 [nan]
 [nan]
 ['F38']
 [nan]
 [nan]
 ['B3']
 [nan]
 ['B20']
 ['D6']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B82 B84']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['D17']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B96 B98']
 [nan]
 [nan]
 [nan]
 ['A36']
 [nan]
 [nan]
 ['E8']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B102']
 [nan]
 [nan]
 [nan]
 [nan]
 ['B69']
 [nan]
 [nan]
 ['E121']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B28']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['E49']
 [nan]
 [nan]
 [nan]
 ['C47']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C92']
 [nan]
 [nan]
 [nan]
 ['D28']
 [nan]
 [nan]
 [nan]
 ['E17']
 [nan]
 [nan]
 [nan]
 [nan]
 ['D17']
 [nan]
 [nan]
 [nan]
 [nan]
 ['A24']
 [nan]
 [nan]
 [nan]
 ['D35']
 ['B51 B53 B55']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['C50']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['B42']
 [nan]
 ['C148']
 [nan]]

In [ ]:
label_enconder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(arr_cabin)
print(integer_encoded)

onehot_encoder=OneHotEncoder(sparse_output=False)
integer_encoded=integer_encoded.reshape(len(integer_encoded),1)
onehot_encoded